#!/bin/bash
# Compile the A0 poster (three bordered columns). All result plots,
# including the DFT formation heatmap, are regenerated by ./make_figures.py
# (run it after new pipeline data).
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p tmp

pdflatex -interaction=nonstopmode -output-directory=tmp poster.tex >/dev/null
pdflatex -interaction=nonstopmode -output-directory=tmp poster.tex >/dev/null

cp tmp/poster.pdf .
echo "Done: poster.pdf"
