#!/bin/bash
# Compile the A0 poster (three bordered columns). Result plots are
# regenerated by ./make_figures.py (run after new pipeline data); the DFT
# formation heatmap is copied from reports/finalPresentation/figures.
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p tmp

pdflatex -interaction=nonstopmode -output-directory=tmp poster.tex >/dev/null
pdflatex -interaction=nonstopmode -output-directory=tmp poster.tex >/dev/null

cp tmp/poster.pdf .
echo "Done: poster.pdf"
