#!/usr/bin/env python3
"""Generate the literature-validation comparison tables for the final deck.

Reads:
    src/literature/literature_comparison.json   (produced by
        ``src/literature/compare.py`` -- ML & MEAM predictions vs ASM/MatWeb
        experimental elastic data for 40+ basis-covered alloys)

Produces:
    sections/_auto_literature_family.tex -- booktabs tabular: per-family MAPE
        for E and nu (ML vs MEAM) + overall row.
    sections/_auto_literature_al.tex     -- booktabs tabular: aluminium drilled
        down by AA series (2/5/6/7xxx), mean literature E + E MAPE.
    Both are \\input by slides/08c_literature_tables.tex.

Run from anywhere; paths resolve relative to this script.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
COMPARISON_JSON = REPO / "src" / "literature" / "literature_comparison.json"
SEC_DIR = HERE / "sections"
SEC_DIR.mkdir(parents=True, exist_ok=True)

# Display order + pretty labels for the material families.
FAMILY_LABELS = {
    "aluminium": "Aluminium",
    "titanium": "Titanium",
    "stainless": "Stainless",
    "nickel_iron": "Ni--Fe (A-286)",
}

# Families left out of the validation table (A-286 is a single record with
# no nu literature value and no valid MEAM run -- not a meaningful row).
EXCLUDED_FAMILIES = {"nickel_iron"}

# Pretty labels for the aluminium alloy series (first digit of the AA number).
AL_SERIES_LABELS = {
    "2xxx": "2xxx (Al--Cu)",
    "5xxx": "5xxx (Al--Mg)",
    "6xxx": "6xxx (Al--Mg--Si)",
    "7xxx": "7xxx (Al--Zn--Mg)",
}


def _load() -> dict:
    if not COMPARISON_JSON.exists():
        raise SystemExit(
            f"missing {COMPARISON_JSON}\n"
            f"Run:  ./phys/bin/python3 src/literature/compare.py"
        )
    with COMPARISON_JSON.open() as fh:
        return json.load(fh)


def _meam_valid(rec: dict) -> bool:
    meam = rec.get("predictions", {}).get("MEAM", {})
    return "error" not in meam and meam.get("physical", True)


_HEADER = ("% AUTO-GENERATED by reports/finalPresentation/"
           "generate_literature_figure.py -- do not edit")


def _subset_mape(records: list[dict], model: str, key: str) -> float | None:
    """MAPE over a subset, from the per-material pct_err blocks.

    For MEAM, only physically valid runs contribute (mirrors compare.py's
    aggregate so a -99 GPa "modulus" can't poison the number).
    """
    errs = []
    for r in records:
        if model == "MEAM" and not _meam_valid(r):
            continue
        blk = r.get("comparison", {}).get(model, {}).get(key)
        if blk and blk.get("pct_err") is not None:
            errs.append(abs(blk["pct_err"]))
    return sum(errs) / len(errs) if errs else None


def _meam_n(records: list[dict]) -> int:
    """Count of physically valid MEAM runs in a subset."""
    return sum(1 for r in records if _meam_valid(r))


def _mean_lit_E(records: list[dict]) -> float | None:
    vals = [r["lit"]["E_GPa"] for r in records if r["lit"].get("E_GPa") is not None]
    return sum(vals) / len(vals) if vals else None


def _fmt(x: float | None, prec: int = 1) -> str:
    return f"{x:.{prec}f}" if x is not None else "---"


def write_family_table(data: dict, out: Path) -> None:
    """Per-family E and ν MAPE (ML vs MEAM) as a booktabs tabular snippet."""
    records = [r for r in data["materials"]
               if r["family"] not in EXCLUDED_FAMILIES]
    meam_on = data["metadata"].get("meam_enabled", True)
    fams = [f for f in FAMILY_LABELS
            if any(r["family"] == f for r in records)]

    lines = [
        _HEADER,
        "\\begin{tabular}{lcccccc}",
        "\\toprule",
        " & & \\multicolumn{2}{c}{$E$ MAPE (\\%)} "
        "& \\multicolumn{2}{c}{$\\nu$ MAPE (\\%)} \\\\",
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
        " Family & $N$ & ML & MEAM & ML & MEAM \\\\",
        "\\midrule",
    ]
    for f in fams:
        rs = [r for r in records if r["family"] == f]
        n = len(rs)
        ml_e = _fmt(_subset_mape(rs, "ML", "E_GPa"))
        ml_nu = _fmt(_subset_mape(rs, "ML", "nu"))
        if meam_on and _meam_n(rs) > 0:
            mm_e = _fmt(_subset_mape(rs, "MEAM", "E_GPa"))
            mm_nu = _fmt(_subset_mape(rs, "MEAM", "nu"))
        else:
            mm_e = mm_nu = "---"
        lines.append(f" {FAMILY_LABELS[f]} & {n} & {ml_e} & {mm_e} "
                     f"& {ml_nu} & {mm_nu} \\\\")
    lines.append("\\midrule")
    n_all = len(records)
    ovr_ml_e = _fmt(_subset_mape(records, "ML", "E_GPa"))
    ovr_ml_nu = _fmt(_subset_mape(records, "ML", "nu"))
    ovr_mm_e = _fmt(_subset_mape(records, "MEAM", "E_GPa")) if meam_on else "---"
    ovr_mm_nu = _fmt(_subset_mape(records, "MEAM", "nu")) if meam_on else "---"
    lines.append(f" \\textbf{{Overall}} & {n_all} & \\textbf{{{ovr_ml_e}}} "
                 f"& {ovr_mm_e} & \\textbf{{{ovr_ml_nu}}} & {ovr_mm_nu} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))
    print(f"[literature] wrote {out}")


def write_aluminium_table(data: dict, out: Path) -> None:
    """Aluminium drilled down by AA series (2/5/6/7xxx) as a tabular snippet."""
    records = data["materials"]
    meam_on = data["metadata"].get("meam_enabled", True)
    al = [r for r in records if r["family"] == "aluminium"]

    def series(rec: dict) -> str | None:
        m = re.match(r"MA(\d)", rec["bassnum"])
        return f"{m.group(1)}xxx" if m else None

    lines = [
        _HEADER,
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        " & & $\\langle E_\\mathrm{lit}\\rangle$ "
        "& \\multicolumn{2}{c}{$E$ MAPE (\\%)} \\\\",
        "\\cmidrule(lr){4-5}",
        " Al series & $N$ & (GPa) & ML & MEAM \\\\",
        "\\midrule",
    ]
    for key, label in AL_SERIES_LABELS.items():
        rs = [r for r in al if series(r) == key]
        if not rs:
            continue
        mm = _fmt(_subset_mape(rs, "MEAM", "E_GPa")) if meam_on else "---"
        lines.append(f" {label} & {len(rs)} & {_fmt(_mean_lit_E(rs))} "
                     f"& {_fmt(_subset_mape(rs, 'ML', 'E_GPa'))} & {mm} \\\\")
    lines.append("\\midrule")
    mm_all = _fmt(_subset_mape(al, "MEAM", "E_GPa")) if meam_on else "---"
    lines.append(f" \\textbf{{All aluminium}} & {len(al)} & "
                 f"{_fmt(_mean_lit_E(al))} & "
                 f"\\textbf{{{_fmt(_subset_mape(al, 'ML', 'E_GPa'))}}} "
                 f"& {mm_all} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))
    print(f"[literature] wrote {out}")


def write_aluminium_detail_table(data: dict, out: Path) -> None:
    """Aluminium resolved to individual alloy grades, with E and nu MAPE.

    One row per AA grade (tempers of a grade share a composition and so a
    prediction; ``N`` counts the datasheet entries collapsed into the row),
    grouped under italic per-series subheaders. Used by the final report only.
    """
    records = data["materials"]
    meam_on = data["metadata"].get("meam_enabled", True)
    al = [r for r in records if r["family"] == "aluminium"]

    def grade(rec: dict) -> str | None:
        m = re.search(r"(\d{4})", rec["name"])
        return m.group(1) if m else None

    def gser(g: str) -> str:
        return f"{g[0]}xxx"

    grades: dict[str, list[dict]] = {}
    for r in al:
        grades.setdefault(grade(r), []).append(r)

    def row(label, rs, bold=False):
        ml_e = _subset_mape(rs, "ML", "E_GPa")
        ml_nu = _subset_mape(rs, "ML", "nu")
        mm_e = _fmt(_subset_mape(rs, "MEAM", "E_GPa")) if meam_on else "---"
        mm_nu = _fmt(_subset_mape(rs, "MEAM", "nu")) if meam_on else "---"
        e_ml = f"\\textbf{{{_fmt(ml_e)}}}" if bold else _fmt(ml_e)
        nu_ml = f"\\textbf{{{_fmt(ml_nu)}}}" if bold else _fmt(ml_nu)
        return (f" {label} & {len(rs)} & {_fmt(_mean_lit_E(rs))} "
                f"& {e_ml} & {mm_e} & {nu_ml} & {mm_nu} \\\\")

    lines = [
        _HEADER,
        "\\begin{tabular}{lrrcccc}",
        "\\toprule",
        " & & & \\multicolumn{2}{c}{$E$ MAPE (\\%)} "
        "& \\multicolumn{2}{c}{$\\nu$ MAPE (\\%)} \\\\",
        "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        " Alloy & $N$ & $\\langle E_\\mathrm{lit}\\rangle$ & ML & MEAM & ML & MEAM \\\\",
    ]
    last = None
    for g, rs in sorted(grades.items(), key=lambda kv: (gser(kv[0]), kv[0])):
        s = gser(g)
        if s != last:
            lines.append("\\midrule")
            lines.append(f" \\multicolumn{{7}}{{l}}{{\\itshape {s} series}} \\\\")
            last = s
        lines.append(row(f"\\quad {g}", rs))
    lines.append("\\midrule")
    lines.append(row("\\textbf{All aluminium}", al, bold=True))
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))
    print(f"[literature] wrote {out}")


def main() -> None:
    data = _load()
    write_family_table(data, SEC_DIR / "_auto_literature_family.tex")
    write_aluminium_table(data, SEC_DIR / "_auto_literature_al.tex")
    write_aluminium_detail_table(data, SEC_DIR / "_auto_literature_al_detail.tex")


if __name__ == "__main__":
    main()
