r"""Shared utilities for the report-asset generators in ``src/stats/``.

Each per-stage script in this folder regenerates one or more figures
(written into ``reports/interim/figures/``) and one or more LaTeX tables
(written into ``reports/interim/sections/`` as ``_auto_<name>.tex``)
using the ``tabulate`` library so that the report can pick them up via
``\input{}`` directives.
"""

from __future__ import annotations

import os
from typing import Sequence

from tabulate import tabulate

# Resolve project layout relative to this file
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.normpath(os.path.join(_THIS_DIR, ".."))
PROJECT_ROOT = os.path.normpath(os.path.join(SRC_DIR, ".."))
REPORT_DIR = os.path.join(PROJECT_ROOT, "reports", "interim")
FIGURES_DIR = os.path.join(REPORT_DIR, "figures")
SECTIONS_DIR = os.path.join(REPORT_DIR, "sections")

# Canonical input data files
RESULTS_JSON = os.path.join(SRC_DIR, "ML", "results.json")
DFT_RESULTS_JSON = os.path.join(SRC_DIR, "NNIP", "dft_results.json")
PIPELINE_SUMMARY_JSON = os.path.join(SRC_DIR, "NNIP", "pipeline_summary.json")


def ensure_dirs() -> None:
    os.makedirs(FIGURES_DIR, exist_ok=True)
    os.makedirs(SECTIONS_DIR, exist_ok=True)


def write_latex_table(
    out_name: str,
    rows: Sequence[Sequence[str]],
    headers: Sequence[str],
    caption: str,
    label: str,
    note: str | None = None,
    floatfmt: str = ".3f",
) -> str:
    """Write a complete LaTeX ``table`` environment to ``sections/<out_name>``.

    The tabular body is produced by ``tabulate(..., tablefmt='latex_raw')``
    so that math-mode tokens such as ``$E$`` survive verbatim. The wrapping
    ``\\begin{table}`` / ``\\caption`` / ``\\label`` are added here so that
    the consumer file only needs ``\\input{sections/<out_name>}``.

    ``floatfmt`` is forwarded to ``tabulate`` so that columns of pre-formatted
    numeric strings (which tabulate re-parses internally) are rendered
    consistently. Defaults to ``.3f`` for the report.
    """
    ensure_dirs()
    body = tabulate(rows, headers=headers, tablefmt="latex_raw",
                    floatfmt=floatfmt)
    note_block = f"\\par\\smallskip\\footnotesize {note}\n" if note else ""
    tex = (
        f"% AUTO-GENERATED by src/stats/ -- do not edit by hand\n"
        f"\\begin{{table}}[h]\n"
        f"\\centering\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"{body}\n"
        f"{note_block}"
        f"\\end{{table}}\n"
    )
    out_path = os.path.join(SECTIONS_DIR, out_name)
    with open(out_path, "w") as f:
        f.write(tex)
    print(f"  wrote {out_path}")
    return out_path


def figure_path(name: str) -> str:
    ensure_dirs()
    return os.path.join(FIGURES_DIR, name)
