"""Flask UI for the alloy elastic-property surrogate.

Wraps :func:`predict_from_model.predict_properties` behind a small JSON
endpoint and serves a single-page form for entering compositions. The model
is loaded lazily on the first prediction request, so ``flask run`` boots
quickly.

Run:
    python app.py            # listens on http://127.0.0.1:5000
"""

from __future__ import annotations

import json
import os
import random
from datetime import datetime, timezone

from flask import Flask, jsonify, render_template, request

from nn_alloy import ALL_ELEMENTS
from predict_from_model import predict_properties

app = Flask(__name__)

# ── Calibration: load nn_metrics.json so the UI can display the model's
# validation-set MAPE alongside each prediction. Loaded once at startup;
# the file is regenerated by ``run_nn.sh`` and re-reading per request would
# just add latency for no benefit.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_METRICS_PATH = os.path.join(_THIS_DIR, "nn_metrics.json")
_MODEL_PATH   = os.path.join(_THIS_DIR, "alloy_model.keras")
_RESULTS_PATH = os.path.join(_THIS_DIR, "results.json")
_CLOUD_MAX    = 800        # rendered SVG dots; ~800 reads dense without lagging


def _load_cloud(max_n: int = _CLOUD_MAX) -> list[dict]:
    """Load (E, ν) ground-truth points for the Ashby-style backdrop.

    Decimates with a fixed seed so the cloud is stable across reloads.
    """
    if not os.path.exists(_RESULTS_PATH):
        return []
    with open(_RESULTS_PATH) as f:
        data = json.load(f)
    pts: list[dict] = []
    for _name, rec in data.items():
        E = rec.get("E_GPa")
        nu = rec.get("nu")
        if not (isinstance(E, (int, float)) and isinstance(nu, (int, float))):
            continue
        if E <= 0 or not (0 < nu < 0.5):
            continue
        pts.append({"E": round(float(E), 3), "nu": round(float(nu), 4)})
    if len(pts) > max_n:
        rng = random.Random(42)        # deterministic so the visual context
        pts = rng.sample(pts, max_n)   # doesn't shuffle on every refresh
    return pts


_CLOUD = _load_cloud()


def _load_calibration() -> dict:
    if not os.path.exists(_METRICS_PATH):
        return {}
    with open(_METRICS_PATH) as f:
        m = json.load(f)
    val   = m.get("val", {})
    train = m.get("train", {})

    def _safe(d: dict, k: str):
        v = d.get(k)
        return v if isinstance(v, (int, float)) else None

    def _stats(d: dict) -> dict:
        return {k: _safe(d, k) for k in (
            "MAE", "RMSE", "MAPE", "R2", "Pearson", "Bias",
            "P95AE", "MedAE", "Std", "true_mean", "true_std",
        )}

    trained_iso = None
    if os.path.exists(_MODEL_PATH):
        ts = os.path.getmtime(_MODEL_PATH)
        trained_iso = datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d")

    val_pass = m.get("val_pass")
    val_fail = m.get("val_fail")
    val_pass_pct = (
        100.0 * val_pass / (val_pass + val_fail)
        if isinstance(val_pass, int) and isinstance(val_fail, int) and (val_pass + val_fail) > 0
        else None
    )

    return {
        # corpus
        "n_total": m.get("n_total"),
        "n_train": m.get("n_train"),
        "n_val":   m.get("n_val"),
        "trained": trained_iso,
        # training meta
        "epochs":        m.get("epochs_trained"),
        "attempts":      m.get("attempts"),
        "gate_passed":   m.get("gate_passed"),
        "max_error_pct": m.get("max_error_pct"),
        "huber_delta":   m.get("huber_delta"),
        "nu_filter_max": m.get("nu_filter_max"),
        "c_scale":       m.get("C_scale"),
        "val_pass":      val_pass,
        "val_fail":      val_fail,
        "val_pass_pct":  val_pass_pct,
        # per-target stats (held-out validation set)
        "val": {
            "E":   _stats(val.get("E_GPa", {})),
            "nu":  _stats(val.get("nu",    {})),
            "C11": _stats(val.get("C11",   {})),
            "C12": _stats(val.get("C12",   {})),
        },
        "train": {
            "E":   _stats(train.get("E_GPa", {})),
            "nu":  _stats(train.get("nu",    {})),
            "C11": _stats(train.get("C11",   {})),
            "C12": _stats(train.get("C12",   {})),
        },
        # legacy convenience: short summaries used in the panel hint + footer
        "mape": {
            "E":   _safe(val.get("E_GPa", {}), "MAPE"),
            "nu":  _safe(val.get("nu",    {}), "MAPE"),
            "C11": _safe(val.get("C11",   {}), "MAPE"),
            "C12": _safe(val.get("C12",   {}), "MAPE"),
        },
        "r2": {
            "E":   _safe(val.get("E_GPa", {}), "R2"),
            "nu":  _safe(val.get("nu",    {}), "R2"),
            "C11": _safe(val.get("C11",   {}), "R2"),
            "C12": _safe(val.get("C12",   {}), "R2"),
        },
    }


_CAL = _load_calibration()

# Tolerance on the composition sum. MD/DFT inputs always normalise to 1.0,
# but the form lets users type free fractions and we'd rather not reject
# input that's off by floating-point noise. We re-normalise on the server
# side and report the original sum so the UI can warn when it's far off.
_SUM_TOLERANCE = 1e-3


@app.route("/")
def index():
    return render_template(
        "index.html",
        elements=ALL_ELEMENTS,
        cal=_CAL,
        cloud=_CLOUD,
    )


def _sensitivity(comp_norm: dict[str, float]) -> list[dict]:
    """Per-element ±10 % perturbation sensitivity of (E, ν).

    For each element with a positive fraction, scale it by (1 ± 0.10) and
    rebalance the *other* elements proportionally so the composition still
    sums to 1.0. Run inference for both signs and report the deltas relative
    to the unperturbed prediction. Two extra forward passes per element ─
    cheap (~5 ms each post-warmup).
    """
    items = [(el, f) for el, f in comp_norm.items() if f > 0]
    if len(items) < 2:
        return []     # single-element compositions have no meaningful tornado

    base = predict_properties(comp_norm)
    base_E, base_nu = base["E_GPa"], base["nu"]
    delta = 0.10
    rows: list[dict] = []
    for el, x in items:
        sum_others = 1.0 - x
        if sum_others <= 1e-9:
            continue        # this element is essentially the whole alloy
        deltas = {}
        for sign, key in ((+1, "plus"), (-1, "minus")):
            new_x = x * (1.0 + sign * delta)
            new_x = max(1e-6, min(0.999999, new_x))
            scale = (1.0 - new_x) / sum_others
            new_comp = {e: f * scale for e, f in comp_norm.items() if e != el}
            new_comp[el] = new_x
            out = predict_properties(new_comp)
            deltas[f"dE_{key}"]  = out["E_GPa"] - base_E
            deltas[f"dnu_{key}"] = out["nu"]    - base_nu
        rows.append({"element": el, "frac": x, **deltas})

    # Sort by max absolute ΔE descending — the engineer's "what matters most".
    rows.sort(key=lambda r: max(abs(r["dE_plus"]), abs(r["dE_minus"])), reverse=True)
    return rows


@app.post("/api/predict")
def api_predict():
    payload = request.get_json(silent=True) or {}
    raw_comp = payload.get("composition", {})
    if not isinstance(raw_comp, dict) or not raw_comp:
        return jsonify(error="Provide a non-empty 'composition' object."), 400

    # Coerce to float, skip blanks, reject negatives. Unknown symbols are
    # left in the dict and surfaced back through 'unknown_elements'.
    comp: dict[str, float] = {}
    for el, val in raw_comp.items():
        if val in (None, "", "null"):
            continue
        try:
            f = float(val)
        except (TypeError, ValueError):
            return jsonify(error=f"Fraction for {el} is not a number: {val!r}"), 400
        if f < 0:
            return jsonify(error=f"Fraction for {el} is negative: {f}"), 400
        if f > 0:
            comp[el] = f

    if not comp:
        return jsonify(error="At least one element must have a positive fraction."), 400

    total = sum(comp.values())
    if total <= 0:
        return jsonify(error="Composition sums to zero."), 400

    # Re-normalise so the model sees a proper mole-fraction vector even if
    # the user typed weights that don't sum to 1.
    normalised = {el: f / total for el, f in comp.items()}

    try:
        out = predict_properties(normalised)
        out["sensitivity"] = _sensitivity(normalised)
    except FileNotFoundError as e:
        return jsonify(error=str(e)), 503

    out["input_sum"] = total
    out["normalised_composition"] = normalised
    return jsonify(out)


if __name__ == "__main__":
    # ``debug=True`` enables auto-reload on file save. Bind to localhost only;
    # this app exposes raw model inference and isn't hardened for the open net.
    app.run(host="127.0.0.1", port=5000, debug=True)
