"""Flask UI for the alloy elastic-property surrogate.

Wraps :func:`predict_from_model.predict_properties` behind a small JSON
endpoint and serves a single-page form for entering compositions. The model
is loaded lazily on the first prediction request, so ``flask run`` boots
quickly.

Run:
    python app.py            # listens on http://127.0.0.1:5000
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from flask import Flask, jsonify, render_template, request

from nn_alloy import ALL_ELEMENTS
from predict_from_model import predict_properties

app = Flask(__name__)

# ── Calibration: load nn_metrics.json so the UI can display the model's
# validation-set MAPE alongside each prediction. Loaded once at startup;
# the file is regenerated by ``run_nn.sh`` and re-reading per request would
# just add latency for no benefit.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_METRICS_PATH = os.path.join(_THIS_DIR, "nn_metrics.json")
_MODEL_PATH = os.path.join(_THIS_DIR, "alloy_model.keras")


def _load_calibration() -> dict:
    if not os.path.exists(_METRICS_PATH):
        return {}
    with open(_METRICS_PATH) as f:
        m = json.load(f)
    val   = m.get("val", {})
    train = m.get("train", {})

    def _safe(d: dict, k: str):
        v = d.get(k)
        return v if isinstance(v, (int, float)) else None

    def _stats(d: dict) -> dict:
        return {k: _safe(d, k) for k in (
            "MAE", "RMSE", "MAPE", "R2", "Pearson", "Bias",
            "P95AE", "MedAE", "Std", "true_mean", "true_std",
        )}

    trained_iso = None
    if os.path.exists(_MODEL_PATH):
        ts = os.path.getmtime(_MODEL_PATH)
        trained_iso = datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d")

    val_pass = m.get("val_pass")
    val_fail = m.get("val_fail")
    val_pass_pct = (
        100.0 * val_pass / (val_pass + val_fail)
        if isinstance(val_pass, int) and isinstance(val_fail, int) and (val_pass + val_fail) > 0
        else None
    )

    return {
        # corpus
        "n_total": m.get("n_total"),
        "n_train": m.get("n_train"),
        "n_val":   m.get("n_val"),
        "trained": trained_iso,
        # training meta
        "epochs":        m.get("epochs_trained"),
        "attempts":      m.get("attempts"),
        "gate_passed":   m.get("gate_passed"),
        "max_error_pct": m.get("max_error_pct"),
        "huber_delta":   m.get("huber_delta"),
        "nu_filter_max": m.get("nu_filter_max"),
        "c_scale":       m.get("C_scale"),
        "val_pass":      val_pass,
        "val_fail":      val_fail,
        "val_pass_pct":  val_pass_pct,
        # per-target stats (held-out validation set)
        "val": {
            "E":   _stats(val.get("E_GPa", {})),
            "nu":  _stats(val.get("nu",    {})),
            "C11": _stats(val.get("C11",   {})),
            "C12": _stats(val.get("C12",   {})),
        },
        "train": {
            "E":   _stats(train.get("E_GPa", {})),
            "nu":  _stats(train.get("nu",    {})),
            "C11": _stats(train.get("C11",   {})),
            "C12": _stats(train.get("C12",   {})),
        },
        # legacy convenience: short summaries used in the panel hint + footer
        "mape": {
            "E":   _safe(val.get("E_GPa", {}), "MAPE"),
            "nu":  _safe(val.get("nu",    {}), "MAPE"),
            "C11": _safe(val.get("C11",   {}), "MAPE"),
            "C12": _safe(val.get("C12",   {}), "MAPE"),
        },
        "r2": {
            "E":   _safe(val.get("E_GPa", {}), "R2"),
            "nu":  _safe(val.get("nu",    {}), "R2"),
            "C11": _safe(val.get("C11",   {}), "R2"),
            "C12": _safe(val.get("C12",   {}), "R2"),
        },
    }


_CAL = _load_calibration()

# Tolerance on the composition sum. MD/DFT inputs always normalise to 1.0,
# but the form lets users type free fractions and we'd rather not reject
# input that's off by floating-point noise. We re-normalise on the server
# side and report the original sum so the UI can warn when it's far off.
_SUM_TOLERANCE = 1e-3


@app.route("/")
def index():
    return render_template("index.html", elements=ALL_ELEMENTS, cal=_CAL)


@app.post("/api/predict")
def api_predict():
    payload = request.get_json(silent=True) or {}
    raw_comp = payload.get("composition", {})
    if not isinstance(raw_comp, dict) or not raw_comp:
        return jsonify(error="Provide a non-empty 'composition' object."), 400

    # Coerce to float, skip blanks, reject negatives. Unknown symbols are
    # left in the dict and surfaced back through 'unknown_elements'.
    comp: dict[str, float] = {}
    for el, val in raw_comp.items():
        if val in (None, "", "null"):
            continue
        try:
            f = float(val)
        except (TypeError, ValueError):
            return jsonify(error=f"Fraction for {el} is not a number: {val!r}"), 400
        if f < 0:
            return jsonify(error=f"Fraction for {el} is negative: {f}"), 400
        if f > 0:
            comp[el] = f

    if not comp:
        return jsonify(error="At least one element must have a positive fraction."), 400

    total = sum(comp.values())
    if total <= 0:
        return jsonify(error="Composition sums to zero."), 400

    # Re-normalise so the model sees a proper mole-fraction vector even if
    # the user typed weights that don't sum to 1.
    normalised = {el: f / total for el, f in comp.items()}

    try:
        out = predict_properties(normalised)
    except FileNotFoundError as e:
        return jsonify(error=str(e)), 503

    out["input_sum"] = total
    out["normalised_composition"] = normalised
    return jsonify(out)


if __name__ == "__main__":
    # ``debug=True`` enables auto-reload on file save. Bind to localhost only;
    # this app exposes raw model inference and isn't hardened for the open net.
    app.run(host="127.0.0.1", port=5000, debug=True)
